### ISSUE TITLE
Installing through NuGet upgrades Umbraco to 7.4.0

### ISSUE THREAD

**Issue by HarveyWilliams** [EndzoneSoftware/uSplit#12]
After reading on http://endzonesoftware.com/installing-usplit/ that uSplit requires version 7.3, and my site was running 7.2.1, I spent some time upgrading to 7.3.8.

When I tried installing uSplit with NuGet, I found that it automatically upgrade to Umbraco 7.4.0 which was quite unexpected.

I think either the documentation needs to updated to say that 7.4.0 is required, or the dependencies need to be changed.

**Comment by HarveyWilliams** [comment]
To get it working I installed all of the packages while ignoring dependencies. This took some time though as I would install a package, reload the site, then see what was still missing.

It has worked though - on my 7.3.8 install I have uSync!

Could the documentation be updated to say that 7.4.x is required?

**Comment by ondrejpialek** [comment]
Hello @HarveyWilliams, thanks for reporting the discrepancy! We are indeed referencing Umbraco 7.4. Over the next few days I will check if we can reference an older version of Umbraco, which would make the plugin available for more people. If not I will update the docs.

**Comment by HarveyWilliams** [comment]
@ondrejpialek I believe trying to install one of the dependencies (with lowest dependency behaviour on) also forced Umbraco to upgrade. I'm not sure which package this was though.

**Comment by ondrejpialek** [comment]
Hi Harvey,

I managed to track the issue to a Newtonsoft.Json Nuget dependency. uSplit 1.0.x requires version 7 and above, whearas Umbraco 7.3 has only version 6 listed as supported.

The documentation already had a note warning about the "surprising" update of Umbraco caused by this dependency chain, I have however updated the document to make it clearer from the very begging that installing it on v 7.3 will be a bit more laborious - you'd have to install it manually as an Umbraco package, rather than via NuGet.

Hope this helps and sorry for the inconveniece.

Cheers,
Ondrej.

**Comment by HarveyWilliams** [comment]
I appreciate you updating the documentation in such detail! Thanks for looking into this.
